### ISSUE TITLE
B&K LAN-XI Type 3160-A-4/2 Issues

### ISSUE THREAD

**Issue by drew-andy** [sandialabs/rattlesnake-vibration-controller#6] opened 2024-06-13 19:39 UTC
I am using the 3.0 Version and While using a LAN-XI data acquisition unit: Physical channel 1 is connected to a transducer that is attached to a shaker. In Feedback channel 1 is teed off and fed into Physical channel 2, and Feedback channel 1 also connected to an amplifier that is connected to the shaker. 
![WIN_20240613_12_21_11_Pro](https://github.com/sandialabs/rattlesnake-vibration-controller/assets/56882392/ba268a1f-fffa-4655-8cb9-0f391903121e)
![WIN_20240613_12_21_26_Pro](https://github.com/sandialabs/rattlesnake-vibration-controller/assets/56882392/8bd7c47b-297c-4672-8751-69ccd2bd3841)
![WIN_20240613_12_21_50_Pro](https://github.com/sandialabs/rattlesnake-vibration-controller/assets/56882392/81106701-893d-4d8c-9fe6-669a7a2709d2)
![WIN_20240613_12_22_06_Pro](https://github.com/sandialabs/rattlesnake-vibration-controller/assets/56882392/051d414a-9431-4347-82bb-2547028f16f9)

I set up the Rattlesnake Channel table as follows: 

![LAN-XI Channel Table](https://github.com/sandialabs/rattlesnake-vibration-controller/assets/56882392/611d8a04-d15e-474c-a85a-c79a665e15c9)

Using the MIMO Random Vibration controller, after attempting to Initialize Data Acquisition, I receive the following error:

![Output Error 03](https://github.com/sandialabs/rattlesnake-vibration-controller/assets/56882392/600ed897-499a-4efe-b6b7-6a9a7c9e4f22)

Do you have any recommendations or examples on Channel table setup and environment definitions for HBKLAN-XI units?

**Comment by drew-andy** [comment] 2024-06-13 19:41
My overall goal is to control a shaker with the Rattlesnake Software and to be able to see the force readings from the transducer as done in BK Connect software. Thank you in advance!

**Comment by dprohe** [comment] 2024-06-18 03:41
Hello and thank you for the error report.  It seems like the issue you are having is connecting to the hardware rather than anything Rattlesnake-specific.  I would check a few things that you've probably already checked, but just to make sure:

- Are you sure you have the correct IP address for the card?  Most of ours typically start with 169.254.XXX.XXX.  Can you check to see that you can access the card via your web-browser?
- Do you have any static IP or subnet masks configured on your ethernet adapter?  Sometimes I run into issues when I configure my ethernet port to run our high-speed cameras, then it stops talking to the data acquisition systems and I have to un-configure it.
- Do you have any firewall settings that might be interfering with the device?  At my workplace I sometimes have issues connecting to the LAN-XI devices due to various network security settings they push on us.  If it is safe to do so, you might try disabling your firewall just to see if it works.  I've also had some success changing the LAN-XI network from public to private, though your network configuration is likely different than mine.
- Have you tried cycling power to your computer/device?  Maybe something is hung up in the device or in your computer's networks settings.
- Have you tried connecting again after it times out?  I can't say I know the reason, but I've seen it where the network will time out the first time, and then it will "figure itself out" and connect the second time.
- Can you connect to the B+K device using the OpenAPI with other software?  For example, could you try running one of the examples here: https://github.com/hbkworld/LAN-XI-Open-API-python-examples? If you can get these to run, but can't get Rattlesnake to run, then it is probably a good bet that the issue is with Rattlesnake.  However if you can't get either to run, then it's probably a problem with your network that you'll have to track down with your IT people.

Unfortunately network issues are really hard to debug because every institution has different firewall settings and network rules which may block or allow important information that the device needs to communicate.

I noticed a couple other things on your channel table that you'll probably need to fix once you get connected.  Your value for coupling should be `22.4 Hz` not `22.4`.  Also, I've had weird issues when using 1 V range where the scaling of the data coming out of the card was off by a factor of 10.  While 1 V is a valid range on LAN-XI, I found setting it to 10 V gave me correct data.  I have a hunch that it might be due to LAN-XI's dual range cards where they simultaneously measure with two different gain settings on their daq to get you better dynamic range.  I'm not sure if their API handles that correctly.  None of these would contribute to your current issue though, it seems like it's not able to talk to the data acquisition at all yet.

**Comment by drew-andy** [comment] 2024-06-18 05:33
Hello, I appreciate your response.

Turns out,  in order to get the LAN-XI to communicate with Rattlesnake I had to put the LAN-XI unit in a recording mode. After I did this I was able to controll my shaker in Rattlesnake's System Identification tab. I also had to add the 'Hz' like you mentioned.

-Now I'm sure this question may sound crazy but what would I put in Load Specifications (npz files)? 

-Is loading control_laws.py OK for the environment definition? 

-How could I get test predictions and a Test profile? 

I'm sorry in advance if these questions sound dumb. I feel like your software is great, I just need some clarification on what is required from the user to get a basic test to run.

**Comment by dprohe** [comment] 2024-06-20 22:31
For the MIMO random vibration, the specification loaded from the .npz (or .mat) file must define a [Cross Power Spectral Density](https://en.wikipedia.org/wiki/Spectral_density#Cross_power_spectral_density) (CPSD) matrix.  It basically tells the controller how much force or acceleration you want at each frequency line in your test.  In your case, since your force sensor will be your control sensor (I assume), it will be in lb^2/Hz or N^2/Hz (I just noticed that your unit on your force sensor in your channel table is set to G, which doesn't really make sensor for a force, is it actually an acceleration?).  Since you only have one channel, it won't really be a CPSD matrix since there won't be any cross-terms between channels if that makes sense, but you still need it to be a 3D matrix, so it will just be a 1 x 1 x n_freq matrix in the case of one channel.

You can construct a CPSD matrix from time histories of a representative response using a function like Matlab's [cpsd](https://www.mathworks.com/help/signal/ref/cpsd.html) or SciPy's [csd](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.csd.html).  Alternatively, there are "standard specifications" like the one from [this issue](https://github.com/sandialabs/rattlesnake-vibration-controller/issues/3) that you can simply read from tables.  There is code in that issue that generates a specification for rattlesnake from the specification the poster showed

When you load in the specification, it should show up in the Environment Definition tab like this:

![image](https://github.com/sandialabs/rattlesnake-vibration-controller/assets/87503982/48961806-da79-4822-9b60-9bd0b10c09b4)

Though note that my example has multiple channels and warning and abort levels built into the specification.  With only one channel and no limits, you should only see the blue curves.

The [User's Manual](https://github.com/sandialabs/rattlesnake-vibration-controller/releases/download/v2.0/Users_Manual.pdf), though a bit out of date for the newest version of the software, shows how a simple specification file should be constructed in section 9.1.

For the control law, you should start by loading in `control_laws.py` and selecting `pseudoinverse_control`.  This is the simplest case that you should start with.

The test predictions appear after you have your environment completely defined (including specification), and you complete the system identification, which allows the controller to determine the relationship between the shaker drive voltage and the responses on the control gauges.  Once the controller has the specification defined and the system identified, only then will it attempt to make a test prediction.

The test profile is only a sequence of events that happens during a test.  If you want to run the test manually by pressing the start and stop buttons, you can just leave the Test Profile tab empty.

**Comment by drew-andy** [comment] 2024-06-21 20:46
Hello and thank you for your guidance. 

That clarified all of my questions. Rattlesnake is definitely a software that is more involved, meaning it requires more background knowledge on the field of structural dynamics to really understand how powerful a tool it actually is. I am enjoying the information I've learned and look forward to setting up tests and collecting some measurements.

**Comment by dprohe** [comment] 2024-06-25 22:49
Glad to hear you're enjoying yourself.  I think with it's ability to simulate tests virtually, Rattlesnake is a great tool for learning how to run these types of tests without the risk of breaking something if you mess up.  If you are interested in learning more about how Rattlesnake works or MIMO testing in general, I've linked some papers from my colleagues here that might be useful.  I'll go ahead and close this issue, and if any other questions come up, feel free to ask.

- [Improving Efficiency of Multi-shaker and Combined Shaker-acoustic Vibration Tests](https://search.proquest.com/openview/09e5d0aac1fd2038c23c8d8769802a52/1?pq-origsite=gscholar&cbl=18750&diss=y) -- A PhD dissertation, so maybe a bit intimidating, but it walks through all of the theory as well, so it could be a good starting point.
- [Sensor Selection for MIMO Vibration](https://www.osti.gov/servlets/purl/1836906) -- Discusses how to place sensors for MIMO vibration tests
- [Strategies for Shaker Placement for Impedance-Matched Multi-Axis Testing](https://www.osti.gov/servlets/purl/1592379) -- Discusses where shakers should be located for MIMO vibration testing.
- [Input signal synthesis for open-loop multiple-input/multiple-output testing](https://www.osti.gov/servlets/purl/1568955) -- Discusses how the signals that get sent to the shakers are generated for MIMO Random Vibration testing.
- [A MIMO Time Waveform Replication Control Implementation](https://www.osti.gov/servlets/purl/2005419) -- Discusses how transient control (controlling to time history responses) can be implemented.

**Closed by dprohe** 2024-06-25 22:49 UTC
Labels: question
